title: Chatbot Standalone
label: Chatbot Standalone
status: alpha
context:
  component-type: element
variants:
  title: "AI Assistant"
  welcome_title: "AI assistant"
  welcome_description: "Welcome! I'm here to help you."
  welcome_message: "Hello! How can I help you today?"
  input_placeholder: "Ask me ..."
  show_suggestions: true
  show_close_button: true
  ai_icon: "../../assets/vf-chatbot/assets/vf-chatbot--icon-16x16-dark-green.svg"
  welcome_logo: "../../assets/vf-chatbot/assets/vf-chatbot--icon-64x64-dark-green.svg"
