title: Chatbot Action Prompt
label: Chatbot Action Prompt
status: live
preview: '@preview'
hidden: true
context:
  component-type: element
  action_text: "Contact Us"
  action_url: "JavaScript:Void(0);"
