title: Link
label: Link
status: live
collated: true
preview: '@preview--nogrid'
context:
  component-type: element
  link_href: "JavaScript:Void(0);"
  buttonType: default
variants:
  - name: default
    hidden: false
    context:
      link_href: "JavaScript:Void(0);"
      text: "A default link"
  - name: example
    context:
      isExample: true

