title: Visual Framework Link
label: Link
status: beta
context:
  component-type: element
variants:
  - name: default
    context:
      href: "#"
      id: "harsh"
      text: "A default link"
  - name: default-hover
    context:
      href: "#"
      style: ["hover"]
      text: "A default:hover link"
  - name: default-visited
    context:
      href: "#"
      style: ["visited"]
      text: "A default:visited link"
  - name: default-disabled
    context:
      href: "#"
      style: ["disabled"]
      text: "A disabled default link"
  - name: primary
    context:
      href: "#"
      id: "harsh"
      text: "A primary link"
  - name: primary-hover
    context:
      href: "#"
      style: ["hover"]
      text: "A primary:hover link"
  - name: primary-visited
    context:
      href: "#"
      style: ["visited"]
      text: "A primary:visited link"
  - name: primary-disabled
    context:
      href: "#"
      style: ["disabled"]
      text: "A disabled primary link"
  - name: secondary
    context:
      href: "#"
      text: A secondary link
      theme: secondary
  - name: secondary-hover
    context:
      href: "#"
      text: A secondary:hover link
      theme: secondary
      style: ["hover"]
  - name: secondary-visited
    context:
      href: "#"
      text: A secondary:visited link
      theme: secondary
      style: ["visited"]
  - name: secondary-disabled
    context:
      href: "#"
      text: A disabled secondary link
      theme: secondary
      style: ["disabled"]
