title: Visual Framework Link
label: Link
preview: '@preview--elements'
status: alpha
context:
  component-type: element

variants:
  - name: default
    context:
      text: An inline link
      class: none
      href: https://example.com/
  - name: secondary
    context:
      text: A secondary link
      class: secondary
      href: https://example.com/
