# Comment to a new issue.
issuesOpened: >

Thank you for raising an issue. We will try and get back to you as soon as possible.

Please make sure you have given us as much context as possible.

# PR Opened
pullRequestOpened: >

Thank you for requesting a review for this pull request (PR).

If this PR has an associated issue - please add that to the PR description.

If you have not done so already - please fill out the PR description with as much context as possible.

# Pull Request Ready For Review
pullRequestReviewRequested: >

Have you added any relevant labels to this PR?

To help this process please make sure you have these things ready (if applicable).

- [ ] `package.json` updated accordingly.
- [ ] `README.md` fill out with required documentation.
- [ ] any `.scss` files correctly documented.
- [ ] a detailed outlin on what this PR is expected to do
