# Comment to a new issue.
issuesOpened: >

  Thank you for raising an issue. We will try and get back to you as soon as possible.

  Please make sure you have given us as much context as possible.

# PR Opened
pullRequestOpened: >

  Thank you for requesting a review for this pull request (PR). If you have not done so already - please fill out the PR description with as much context as possible.<br/>

  If this PR has an associated issue - please add that to the PR description.

  ## Pull request review

  Before your PR can be merged in, it will need to be reviewed.

  - [ ] a detailed outline on what this PR is expected to do

  - [ ] add relevant labels to this PR

  - [ ] `package.json` is updated accordingly

  - [ ] `README.md` is filled out with required documentation

  - [ ] `CHNAGELOG.md` is updated

  - [ ] any `.scss` files correctly documented
