# The title shown on the component page
title: Social Icons
# Label shown on index pages
label: Social Icons
status: alpha
context:
  component-type: block

  heading: follow us
  social_accounts:
    - name: twitter
      url: https://www.twitter.com
      useUrl: "#vf-social--twitter"
    - name: facebook
      url: https://www.facebook.com
      useUrl: "#vf-social--facebook"
    - name: instagram
      url: https://www.instagram.com
      useUrl: "#vf-social--instagram"
    - name: youtube
      url: https://www.youtube.com
      useUrl: "#vf-social--youtube"
    - name: linkedin
      url: https://www.linkedin.com
      useUrl: "#vf-social--linkedin"
