# The title shown on the pattern page
title: embl-core
# Label shown on index pages
label: embl-core
status: alpha
# The template used from /components/_previews
# preview: '@preview--blocks'
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  pattern-type: core
  # custom-values: passed as {{custom-values}}
