title: Modular VF Footer
label: Modular VF Footer
preview: '@preview--nogrid'
status: live
context:
  footer__theme: 'dark'
  component-type: container
  hide-from-sitemenu: true
  partner__variant: null
  footer__show_logo: true
  footer__show_mission: true
  footer__show_social: true
  footer__show_contact: true
  footer__show_sublinks: false
  footer__show_intro_notice: false
variants:
  - name: Light Modular Footer
    title: Light Modular Footer
    context:
      footer__theme: 'light'
      partner__variant: null
      footer__show_logo: true
      footer__show_mission: true
      footer__show_social: true
      footer__show_contact: true
      footer__show_sublinks: false
      footer__show_intro_notice: false
  - name: partner logos
    title: Partner Logos
    context:
      footer__theme: 'dark'
      partner__variant: logos
      footer__show_logo: true
      footer__show_mission: true
      footer__show_social: true
      footer__show_contact: true
      footer__show_sublinks: false
      footer__show_intro_notice: false
  - name: partner columns
    title: Partner Columns
    context:
      footer__theme: 'dark'
      partner__variant: columns
      footer__show_logo: true
      footer__show_mission: true
      footer__show_social: true
      footer__show_contact: true
      footer__show_sublinks: false
      footer__show_intro_notice: false
  - name: partner summary
    title: Partner Summary
    context:
      footer__theme: 'dark'
      partner__variant: summary
      footer__show_logo: true
      footer__show_mission: true
      footer__show_social: true
      footer__show_contact: true
      footer__show_sublinks: false
      footer__show_intro_notice: false
  - name: Legacy Footer
    title: Legacy Footer
    context:
      footer__theme: 'dark'
      partner__variant: null
      footer__show_logo: false
      footer__show_mission: false
      footer__show_social: false
      footer__show_contact: false
      footer__show_sublinks: true
      footer__show_intro_notice: true
