title: Fieldset
label: Fieldset
status: beta

context:
  component-type: form

variants:
  - name: default
    context:
      fieldset_legend:
        legend__text: A Fieldset Legend
  - name: error
    context:
      fieldset__error:
        error: true
        helper_text: Something has gone terribly wrong.
      fieldset_legend:
        legend__text: Another Fieldset Legend
