# The title shown on the component page
title: ELIXIR Banner
# Label shown on index pages
label: Banner for ELIXIR services
status: alpha
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   label: Default
  #   hidden: true
  #   context:
  #     children_are_possible:
  #       variant_title: A Easy Card Title 1
  #       variant_href: "JavaScript:Void(0);"
  #       modifier: vf-card--very-easy
  #       variant_image: ../../assets/vf-card/assets/vf-card-example.png
# Global component context
context:
  component-type: container
  # custom-values: passed as {{custom-values}}
  # - note: you in your custom-values you should use dashes `-`
  #         and not underscores `_` as underscores prevent inherited template use
  logo: default
  # logo: cdr # to use the ELIXIR CDR logo instead
  name: Service Name
  description: A short description about this service's role and function
  link: default
  # link: //or-a-link-about-your-relationship-with-elixir
