title: Flag
label: Flag
status: alpha

context:
  component-type: layout

variants:
  - name: top
    context:
      top: true
  - name: middle
    context:
      middle: true
  - name: bottom
    context:
      bottom: true
  - name: reversed
    context:
      reversed: true
  - name: reversed top
    context:
      reversed: true
      top: true
  - name: reversed middle
    context:
      reversed: true
      middle: true
  - name: reversed bottom
    context:
      reversed: true
      bottom: true
