# The title shown on the component page
title: Demonstration deprecated pattern
# Label shown on index pages
label: Deprecated pattern
status: deprecated
# hidden: true
# The template used from /components/_previews
# preview: '@preview--blocks'
# Per-variant options
variants:
  - name: default
    hidden: true
context:
  component-type: deprecated
  # custom-values: passed as {{custom-values}}
