# The title shown on the component page
title: Details
# Label shown on index pages
label: Details
status: beta
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
    label: Default
    # hidden: true
    context:
      details_open: true
      details_summary: I'm a detail
      details_content: Something small enough to escape casual notice.
# Global component context
context:
  component-type: container
  # custom-values: passed as {{custom-values}}
  # - note: you in your custom-values you should use dashes `-`
  #         and not underscores `_` as underscores prevent inherited template use
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
