title: Grid
label: Grid
preview: '@preview--nogrid'
status: live
context:
  component-type: layout

variants:
  - name: default
    hidden: true
  - name: auto
    label: Auto Layout
  - name: col-2
    label: 2 Columns
    context:
      vf_grid__columns: 2
  - name: col-3
    label: 3 Columns
    context:
      vf_grid__columns: 3
  - name: col-4
    label: 4 Columns
    context:
      vf_grid__columns: 4
  - name: col-5
    label: 5 Columns
    context:
      vf_grid__columns: 5
  - name: col-6
    label: 6 Columns
    context:
      vf_grid__columns: 6
