server {
    listen 8080;
    server_name localhost _;

    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_min_length 256;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml application/xml+rss text/javascript font/ttf font/otf font/woff font/woff2 application/vnd.ms-fontobject;
    gzip_static on;

    server_tokens off;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header Content-Security-Policy "base-uri 'self'" always;
    add_header X-Xss-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff";

    location / {
      try_files $uri $uri/ /index.html;
    }

    location = /healthcheck {
      default_type text/plain;
      return 200 "ok";
    }

    location /favicon.ico {
      expires 7d;
    }

    location /robots.txt {
      expires 1d;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2?|svg|ttf|eot|otf|mp4|webm|webp|pdf)$ {
      try_files $uri =404;
      expires max;
      log_not_found off;
    }

    location ~* /(\.htaccess|\.git|\.env|\.htpasswd) {
      deny all;
    }

    location ~ \.(phtml|php3|php4|php5|pl|py|jsp|asp|exe|shtml|sh|cgi|suspected|7z|aspx|bak|bz|bz2|cer|cgi|conf|crt|gz|ini|key|log|pem|php7|rar|sql|tar|zip|phar|java)$ {
      deny all;
    }

    location ~ /\.ht {
      deny all;
    }
}
