title: Chatbot Feedback Component
label: Chatbot Feedback
status: alpha
context:
  positiveFeedbackOptions:
    - 'Accurate answer'
    - 'Easy to understand'
    - 'Well formatted'
    - 'Helpful'
  negativeFeedbackOptions:
    - 'Inaccurate answer'
    - 'Did not use context'
    - 'Poorly formatted'
    - 'Not helpful'
