title: Chatbot Feedback
label: Chatbot Feedback
status: beta
preview: '@preview'
hidden: true
context:
  component-type: element
variants:
  - name: positive
    context:
      options:
        - id: "accurate"
          label: "Accurate answer"
        - id: "easy"
          label: "Easy to understand"
        - id: "formatted"
          label: "Well formatted"
        - id: "helpful"
          label: "Helpful"
  - name: negative
    context:
      options:
        - id: "inaccurate"
          label: "Inaccurate answer"
        - id: "nocontext"
          label: "Did not use context"
        - id: "poorformat"
          label: "Poorly formatted"
        - id: "nothelpful"
          label: "Not helpful"
