title: Logo
label: Logo
preview: '@preview--elements'
context:
  component-type: element
  href: http://www.embl.de
  sreen_reader_text: Visual Framework 2.0
  image: '/assets/vf-logo/assets/logo.png'
