# The title shown on the component page
title: Logo
# Label shown on index pages
label: Logo
status: live
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
    context:
      hidden_text: false
  - name: extreme
    context:
      override_class: vf-logo--extreme
      hidden_text: false
  - name: hidden text
    context:
      hidden_text: true
  - name: extreme with hidden text
    context:
      override_class: vf-logo--extreme
      hidden_text: true
context:
  # custom-values: passed as {{custom-values}}
  component-type: element
  logo_href: http://www.embl.de
  logo_text: Visual Framework 2.0
  image: https://assets.emblstatic.net/vf/v2.4.6/assets/vf-logo/assets/logo.svg
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
