title: Sidebar Layout
label: Sidebar Layout
status: alpha

context:
  component-type: layout

variants:
  - name: default
    hidden: true
  - name: start
    context:
      sidebar_position: left
  - name: end
    context:
      sidebar_position: right
  - name: start 200
    context:
      sidebar_position: start
      sidebar_spacing: 200
  - name: end 400
    context:
      sidebar_position: end
      sidebar_spacing: 400
  - name: start 500
    context:
      sidebar_position: left
      sidebar_spacing: 500
  - name: end 600
    context:
      sidebar_position: right
      sidebar_spacing: 600
  - name: start 800
    context:
      sidebar_position: start
      sidebar_spacing: 800
  - name: end 1200
    context:
      sidebar_position: end
      sidebar_spacing: 1200
  - name: start 1600
    context:
      sidebar_position: left
      sidebar_spacing: 1600

  - name: start 400 80
    context:
      sidebar_position: start
      sidebar_spacing: 400
      sidebar__main_content_width: "80%"

