title: Sidebar Layout
label: Sidebar Layout
status: alpha

context:
  component-type: layout

variants:
  - name: default
    hidden: true
  - name: start
    context:
      sidebar_main: left
  - name: end
    context:
      sidebar_main: right
