title: Chatbot Modal
label: Chatbot Modal
status: alpha
version: 0.0.1
preview: '@preview'
context:
  title: AI Assistant
  welcome_message: Hello! How can I help you today?
  input_placeholder: Type your message...
  show_suggestions: true
  disclaimer: 'Disclaimer: This chatbot is designed to assist you with general information and basic inquiries. See our <a class="vf-banner__link" href="JavaScript:Void(0);">disclaimer notes</a>.'
