title: Summary Container
label: Summary Container
preview: '@preview--containers'
context:
  pattern-type: container
  section-title: Learn about Cancer
  item01:
    summary__title: What is Cancer?
    summary__text: Cancer is a group of diseases involving abnormal cell growth with the potential to invade or spread to other parts of the body.
  item02:
    summary__title: Cancer and EMBL
    summary__text: EMBL researchers use both computational and traditional lab research to try and understand why cancer happens and how cancer grows and spreads. They can sample and test how tumours and drugs react and find unique molecular data to identify diseases.
  item03:
    summary__title: What does Cancer look like?
    summary__text: Cancer is caused by uncontrolled cell division. These cells are tiny, but but can quickly add up and cancerous cells can look very different from healthy ones.
