apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${PROJECT_NAMESPACE_PROD}

resources:
  - ../../base

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      env: prod

configMapGenerator:
  - name: ${PROJECT_NAME_SANITISED}-env-config
    envs:
      - ./.env

patches:
  - path: ./patch-web.yaml
