apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          env:
            - name: ENV
              value: "prod"
            - name: DATACENTER
              value: "hh"
            - name: DB_DATACENTER
              value: "pg"
            - name: HTTP_PROXY
              value: "http://pg-wwwcache.ebi.ac.uk:3128"
            - name: HTTPS_PROXY
              value: "http://pg-wwwcache.ebi.ac.uk:3128"
