title: Data Protection Banner
label: Data Protection
preview: '@preview--nogrid'
context:
  pattern-type: block
  data-service-id: MyService
  data-protection-version: 0.1
  vf-data-protection-banner__text:
  vf-data-protection-banner__link: I agree, dismiss this banner
