title: Tags
label: Tags
preview: '@preview--elements'
collated: true
variants:
  - name: default
    hidden: true
  - name: examples
    hidden: false
  - name: outline
    hidden: true
  - name: sizes
    hidden: true
  - name: styles
    hidden: true
  - name: variants
    hidden: true
context:
  pattern-type: element
  vf-tag-name: alpha
