# The title shown on the component page
title: Back to top
# Label shown on index pages
label: Back to top
status: alpha
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
    hidden: true
  - name: inline
    label: Inline
    hidden: false
    context:
      type: inline
      scrollToId: top
      example: true
      angular: <vf-back-to-top [type]="'inline'" [text]="'Top'" [scrollToId]="'top'" [example]="true"></vf-back-to-top>
  - name: floating
    label: Floating
    hidden: false
    context:
      type: floating
      example: true
      angular: <vf-back-to-top [type]="'floating'" [example]="false"></vf-back-to-top>
# Global component context
context:
  exampleMultiColumns: "false"
  component-type: block
  # custom-values: passed as {{custom-values}}
  # - note: you in your custom-values you should use dashes `-`
  #         and not underscores `_` as underscores prevent inherited template use
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
