title: Lists
label: Lists
status: live
context:
  component-type: element
variants:
  - name: default
    context:
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: inline
    context:
      list_type: inline
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: ordered
    context:
      list_type: ordered
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: unordered
    context:
      list_type: unordered
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
