title: Visual Framework Lists
label: Lists
preview: '@preview--elements'
status: alpha
collated: true
variants:
  - name: default
    label: Block
    title: "vf-list pattern: Block"
context:
  pattern-type: element
