title: Lists
label: Lists
status: live
context:
  component-type: element
variants:
  - name: default
    context:
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: tight
    context:
      list_type: default
      override_class: vf-list--tight
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: large
    context:
      list_type: l
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: inline
    context:
      list_type: inline
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: ordered
    context:
      list_type: ordered
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: unordered
    context:
      list_type: unordered
      list:
        - a list item
        - another list item
        - and another list item
        - yet another list item
  - name: definition
    context:
      list_type: definition
      list:
        - term: Beast of Bodmin
          definition: A large feline inhabiting Bodmin Moor.
        - term: Morgawr
          definition: A sea serpent.
        - term: Owlman
          definition: A giant owl-like creature.
