title: The Snippet
label: Snippet
preview: '@preview--blocks'
context:
  pattern-type: block
  snippet-heading: EMBL's top social media posts of 2017 and what we learned from them
  snippet-author: Laura Howes
  snippet-date: 06 February 2018
  snippet-meta-link: Leave Comment
  snippet-teaser-text: I want to take a look back at my first full year as EMBL's social media manager. So what worked best over 2017 and what can I learn from this? My basic goals for VF’s social media are to build community and develop a shared understanding of who we as an organisation are. Consequently, I care about what resonates on the different social sites much more than driving traffic back to Visual Framework websites, although traffic is obviously a by-product.
  snippet-teaser-link: Read More
