title: Input
label: Input

context:
  component-type: form

variants:
  - name: search
    context:
      search_placeholder: Search all of EMBL.org
  - name: filter
    context:
      search_placeholder: Search this book
