# The title shown on the component page
title: EMBL-EBI Header and Footer
# Label shown on index pages
label: EMBL-EBI Header and Footer
status: live
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
# preview: '@preview--nogrid'
context:
  component-type: utility
  disable_ebi_1x_cookie_banner: true
  # custom-values: passed as {{custom-values}}
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
