title: Activity List
label: Activity List
status: deprecated
component-type: deprecated
hidden: true
context:
  component-type: block
  date: Tuesday 20th February 2018
  list:
    - <strong>Sonia Furtado Neves</strong> published <a href="JavaScript:Void(0);">'The Future of Training'</a> on <a href="JavaScript:Void(0);">EMBL News</a>.
    - <strong>Sonia Furtado Neves</strong> published <a href="JavaScript:Void(0);">'The Future of Training'</a> on <a href="JavaScript:Void(0);">EMBL News</a>.
    - <strong>Mark Boulton</strong> updated <a href="JavaScript:Void(0);">Digital Strategy</a> on <a href="JavaScript:Void(0);">Gitlab</a> to version 1.1, with the comment <blockquote class="vf-activity__blockquote | vf-blockquote">Additional detail added to social section.</blockquote>
