# The title shown on the pattern page
title: vf-simple-search
# Label shown on index pages
label: vf-simple-search
status: alpha
# The template used from /components/_previews
# preview: '@preview--blocks'
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  pattern-type: block
  # custom-values: passed as {{custom-values}}
