#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

echo "[Husky Prepush]"
# Pre-push disabled until errors resolved
# https://github.com/visual-framework/vf-core/pull/1373#issuecomment-789915125
# cd tools/vf-core
# yarn run gulp vf-prepush-test
