# The title shown on the component page
title: Dropdown
# Label shown on index pages
label: Dropdown
status: alpha
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: default
    context:
      label: John doe
      width: 14rem
      labelAlign: left
      menuItems:
        - text: Profile
          link_href: JavaScript:Void(0);
        - text: Settings
          link_href: JavaScript:Void(0);
        - text: Logout
          link_href: JavaScript:Void(0);
        - text: EBI Home
          link_href: https://www.ebi.ac.uk/
# Global component context
context:
  component-type: block
  # custom-values: passed as {{custom-values}}
  # - note: you in your custom-values you should use dashes `-`
  #         and not underscores `_` as underscores prevent inherited template use
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
