name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and test
      run: |
        npm install -g yarn
        npm install -g gulp
        cd tools/vf-core
        yarn install
        gulp vf-build # to do: we should make this run by `npm test`
      env:
        CI: true
