name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and test
      run: |
        npm install -g yarn
        npm install -g gulp
        yarn install
        cd tools/vf-core
        gulp vf-build # to do: we should make this run by `npm test`
      env:
        CI: true
